### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by nikx1015** [NewForce-at-Mountwest/nutshell-team-hedgehopper-1#9]
One teammate, and only one, should follow these steps and complete this ticket.

1. Clone this repo onto your local machine.
2. Switch to a new branch.
3. Run the `setUpBrowserify` function in your `.bashrc` file.
4. Add the following line of code to your .gitignore so that Git will ignore your `bundle.js` file (don't worry, it'll rebuild itself every time you run `grunt`).

```
public/*.js
```
1. Add and commit your new files.
2. Push up your changes to your branch and create a PR.
3. When your teammates test your PR, they should fetch your branch and try running `npm i` in the `lib` directory. Then they should be able to run `grunt` without errors.

Once the PR has been merged in, _everyone_ on the team should pull down master, go into the `src/lib` directory, and run `npm i` to install all the dependencies.

**Comment by Downeastrussell** [comment]
completed
